### ISSUE TITLE
When Datapoint is generated, stored information is always DDA params, even in DIA module

### ISSUE THREAD

**Issue by rodvrees** [Proteobench/ProteoBench#434]
While DIA-specific params are being parsed from parameter files, generate_datapoint always outputs datapoints with the same set of attributes, which were based on the DDA-parsed params, effectively ignoring a  chunk of the other parameters.
https://github.com/Proteobench/ProteoBench/blob/213ac847c679dc2caa78495be4dd5121ac6a1c8e/proteobench/datapoint/quant_datapoint.py#L76-L106

**Comment by rodvrees** [comment]
https://proteobench.readthedocs.io/en/stable/available-modules/4-DIA-Quantification/#input-data-for-private-visualisation-of-your-benchmark-run-s

For example, the parameters shown here are not the same as for DDA but those for DDA are visualized

**Comment by RobbinBouwmeester** [comment]
So this is fixed @rodvrees

**Comment by wolski** [comment]
Does this relate to?

https://github.com/Proteobench/ProteoBench/blob/671a7b9b965712751312fcb45fa7beeb8dd3eb80/proteobench/io/params/__init__.py#L89-L94

**Comment by rodvrees** [comment]
Yes, exactly. I have a minor problem with that there is one specified list of parsed parameters (and also 1 specific list of parameters that are plotted on the main plots). 

https://github.com/Proteobench/ProteoBench/blob/671a7b9b965712751312fcb45fa7beeb8dd3eb80/proteobench/plotting/plot_quant.py#L129-L143

Right now this is not a massive problem I think, but if we have very specific modules in the future, we might want to parse and plot other -more applied- parameters.

**Comment by rodvrees** [comment]
So, looking back to this. It currently isn't fixed, but everything is in place to fix it, even though it might be convoluted.
Currently, the ProteoBenchParameters class init method takes a parameter "filename" pointing to a module-specific json containing the parameter fields that need to end up in the parsed parameters. However, right now, this parameter is defaulted to the fields for the quant_lfq_ion_dda_fields.json, and nowhere is ProteoBenchParameters initialized with another value for "filename". This causes, for example, that the "DIA_second_pass" is never actually parsed.

The way to fix the DIA-DDA parameter question, would be quite straightforward, i.e. by changing the "filename" parameter when ProteoBenchParameters is initialized in each param parsing module for each DIA-specific search engine.

However, if we want the param parsing to be fully module-specific and not just DDA/DIA specific, we need to go a bit further and actually pass the filename parameter through the whole param parsing workflow. This is definitely doable but quite convoluted, I think.

**Comment by RobbinBouwmeester** [comment]
Is fixed now in the `webinterface/pages/pages_varaiables/*` in the variable `additional_params_json`
